### ISSUE TITLE
Parameter problem?

### ISSUE THREAD

**Issue by LaKing** [oskosk/express-socket.io-session#19]
Could someone give me a hint about this? 

```javascript
url.js:73
throw new TypeError("Parameter 'url' must be a string, not " + typeof url);
^

TypeError: Parameter 'url' must be a string, not undefined
at Url.parse (url.js:73:11)
at urlParse (url.js:67:5)
at session (project/node_modules/express-session/index.js:98:24)
at project/node_modules/express-socket.io-session/index.js:66:7
```

**Comment by dodekeract** [comment]
No, not without a code sample `||` explanation.

**Comment by knoxcard** [comment]
If you have not figured this out already, this bug is incredible simple as it is what is state.

var url = 'http://www.yahoo.com'
console.log(url)

you probably have...
```
var url = typeof('http://www.yahoo.com/')
console.log(url)
```
which is okay...but you are missing something and have something like this...
```
var url = typeof 'http://www.yahoo.com/'
console.log(url)

```
