### ISSUE TITLE
expressSessionMiddleware

### ISSUE THREAD

**Issue by ArmandArthur** [oskosk/express-socket.io-session#29]
Hello, i read the documentation et i have this error, what do i miss?

```
C:\wamp64\www\node_modules\express-socket.io-session\index.js:66
      expressSessionMiddleware(req, res, function(req, res) {
      ^

TypeError: expressSessionMiddleware is not a function
    at C:\wamp64\www\node_modules\express-socket.io-session\index.js:66:7
    at cookieParser (C:\wamp64\www\node_modules\cookie-parser\index.js:48:5)
    at Array.socketIoSharedSessionMiddleware (C:\wamp64\www\node_modules\express-socket.io-session\index.js:61:5)
    at run (C:\wamp64\www\node_modules\socket.io\lib\namespace.js:123:11)
    at Namespace.run (C:\wamp64\www\node_modules\socket.io\lib\namespace.js:135:3)
    at Namespace.add (C:\wamp64\www\node_modules\socket.io\lib\namespace.js:163:8)
    at Client.connect (C:\wamp64\www\node_modules\socket.io\lib\client.js:76:20)
    at Server.onconnection (C:\wamp64\www\node_modules\socket.io\lib\index.js:398:10)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
```
```

**Comment by oskosk** [comment]
When you first invoke the function exported by this module, you have to call it with the original express-session function as first parameter.


From the README.md on this repo, the usage is as follows:

```
var session = require("express-session")({
    secret: "my-secret",
    resave: true,
    saveUninitialized: true
});
var sharedsession = require("express-socket.io-session");

// Use express-session middleware for express
app.use(session);

// Use shared session middleware for socket.io
// setting autoSave:true
io.use(sharedsession(session, {
    autoSave:true
})); 
```

Here's the key:
```
io.use(sharedsession(session, {
    autoSave:true
})); 
```

you probably are not passing `session` in the call to the function exported by this module.

**Comment by oskosk** [comment]
Closing as issue author has not come back in a while
