### ISSUE TITLE
Destroy session HTTPS error

### ISSUE THREAD

**Issue by Blamo27** [oskosk/express-socket.io-session#65]
@oskosk 

```LOG
/var/website/node_modules/express-socket.io-session/index.js:96
return originalId === sess.id && savedHash === hash(sess);
                                               ^
TypeError: Cannot read property 'id' of undefined
  at isSaved (/var/website/node_modules/express-socket.io-session/index.js:96:30)
  at shouldSave (/var/website/node_modules/express-socket.io-session/index.js:112:8)
  at /var/website/node_modules/express-socket.io-session/index.js:66:10
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

Work without HTTPS .. 😢

**Comment by Blamo27** [comment]
@oskosk ?

**Comment by durek1337** [comment]
Same issue here when calling session.destroy() or setting session to null. In http.
